
import { Achievement, Language, Subject, ShopItem, Stock, Boss, AccentColor, FirebaseConfig } from './types';
import { Sparkles, Shield, Zap, Palette, BookOpen } from 'lucide-react';
import React from 'react';

// --- CONFIGURATION ---
export const GEMINI_API_KEY = "AIzaSyD0EZELv8tWp4NkqDR04EJm41icVtYkXoo";

export const FIREBASE_CONFIG: FirebaseConfig = {
  apiKey: "AIzaSyDqLKUzjhftF5IrDUdLBEyELbvZ7ozKo_g",
  authDomain: "lumina-fecd9.firebaseapp.com",
  projectId: "lumina-fecd9",
  storageBucket: "lumina-fecd9.firebasestorage.app",
  messagingSenderId: "419584547844",
  appId: "1:419584547844:web:cd0a35c2514850616ce951",
  measurementId: "G-68L1PK71M2"
};

export const LEVEL_THRESHOLDS = [0, 100, 300, 600, 1000, 1500, 2100, 3000, 5000, 10000, 20000];

export const DEFAULT_SUBJECTS: Subject[] = [
  { id: 'math', name: 'Mathematics', totalMinutes: 0, sessionsCount: 0 },
  { id: 'lit', name: 'Literature', totalMinutes: 0, sessionsCount: 0 },
  { id: 'sci', name: 'Science', totalMinutes: 0, sessionsCount: 0 },
  { id: 'code', name: 'Programming', totalMinutes: 0, sessionsCount: 0 },
];

export const ACCENT_COLORS: { [key in AccentColor]: string } = {
  'monochrome': '#000000',
  'neon-green': '#39ff14',
  'electric-blue': '#00ffff',
  'crimson-red': '#dc143c',
  'cyber-yellow': '#ffd700',
};

export const SHOP_ITEMS: ShopItem[] = [
  { id: 'freeze', name: 'Streak Freeze', cost: 500, type: 'consumable', icon: React.createElement(Shield, { size: 16 }), effect: 'Prevents streak loss' },
  { id: 'xp_boost', name: 'XP Potion (1h)', cost: 300, type: 'consumable', icon: React.createElement(Zap, { size: 16 }), effect: '2x XP for 1 hour' },
  { id: 'theme_neon', name: 'Neon Theme', cost: 1000, type: 'cosmetic', icon: React.createElement(Palette, { size: 16 }) },
  { id: 'pet_food', name: 'Digital Berries', cost: 50, type: 'consumable', icon: React.createElement(Sparkles, { size: 16 }), effect: 'Feeds pet' },
];

export const MOCK_STOCKS: Stock[] = [
  { symbol: 'LUM', name: 'Lumina Corp', price: 124.50, trend: 'up', owned: 0 },
  { symbol: 'FOC', name: 'Focus Tech', price: 45.20, trend: 'down', owned: 0 },
  { symbol: 'BRN', name: 'Brain Trust', price: 890.00, trend: 'flat', owned: 0 },
];

export const BOSS_TEMPLATES: Boss[] = [
  { id: 'proc_demon', name: 'Procrastination Demon', hp: 1000, maxHp: 1000, level: 1, image: '👹', description: 'Feeds on idle time.' },
  { id: 'distract_dragon', name: 'Distraction Dragon', hp: 2500, maxHp: 2500, level: 5, image: '🐉', description: 'Breathes notifications.' },
  { id: 'entropy_king', name: 'Entropy King', hp: 10000, maxHp: 10000, level: 20, image: '👑', description: 'The chaos of the universe.' },
];

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'novice',
    title: { en: 'Novice Scholar', hu: 'Kezdő Tanuló' },
    description: { en: 'Complete your first study session.', hu: 'Fejezd be az első tanulási szakaszodat.' },
    icon: '🌱',
    condition: (user) => user.sessions.length >= 1,
  },
  {
    id: 'dedicated',
    title: { en: 'Dedicated', hu: 'Elhivatott' },
    description: { en: 'Reach Level 3.', hu: 'Érd el a 3. szintet.' },
    icon: '🔥',
    condition: (user) => user.level >= 3,
  },
  {
    id: 'marathon',
    title: { en: 'Marathon Runner', hu: 'Maratonfutó' },
    description: { en: 'Study for over 1000 minutes total.', hu: 'Tanulj összesen több mint 1000 percet.' },
    icon: '🏃',
    condition: (user) => user.sessions.reduce((acc, s) => acc + s.durationMinutes, 0) >= 1000,
  },
  {
    id: 'polymath',
    title: { en: 'Polymath', hu: 'Polihisztor' },
    description: { en: 'Study 3 different subjects.', hu: 'Tanulj 3 különböző tantárgyat.' },
    icon: '🧠',
    condition: (user) => {
        const uniqueSubjects = new Set(user.sessions.map(s => s.subjectId));
        return uniqueSubjects.size >= 3;
    }
  },
  {
    id: 'boss_slayer',
    title: { en: 'Boss Slayer', hu: 'Főnökölő' },
    description: { en: 'Defeat a boss in Battle Mode.', hu: 'Győzz le egy főellenséget.' },
    icon: '⚔️',
    condition: (user) => user.activeBoss === undefined && user.level > 2 // Simplified condition
  }
];

export const TRANSLATIONS = {
  [Language.EN]: {
    // ... Existing ...
    login: 'Login',
    register: 'Register',
    username: 'Username',
    password: 'Password',
    welcome: 'Welcome back',
    startJourney: 'Start your journey',
    dashboard: 'Dashboard',
    subjects: 'Subjects',
    achievements: 'Achievements',
    history: 'History',
    settings: 'Settings',
    focus: 'Focus',
    shortBreak: 'Short Break',
    longBreak: 'Long Break',
    start: 'Start',
    pause: 'Pause',
    reset: 'Reset',
    sessionComplete: 'Session Complete!',
    whatDidYouStudy: 'What did you study?',
    selectSubject: 'Select Subject',
    saveSession: 'Save Session',
    minutes: 'minutes',
    level: 'Level',
    xp: 'XP',
    nextLevel: 'Next Level',
    logout: 'Logout',
    theme: 'Theme',
    language: 'Language',
    addSubject: 'Add Subject',
    subjectName: 'Subject Name',
    create: 'Create',
    cancel: 'Cancel',
    totalTime: 'Total Time',
    aiTip: 'AI Study Tip',
    getAiTip: 'Get AI Motivation',
    loadingAi: 'Thinking...',
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    enterDetails: "Enter session details to claim your XP!",
    notesPlaceholder: "I learned about...",
    volume: "Ambience Volume",
    dailyQuests: "Daily Quests",
    rankings: "Rankings",
    aiLab: "AI Lab",
    explainConcept: "Explain Concept",
    explainPlaceholder: "e.g., Quantum Entanglement, French Revolution...",
    simplify: "Simplify it",
    studyPlanner: "Study Planner",
    plannerPlaceholder: "e.g., I have 2 hours for Biology exam...",
    generatePlan: "Generate Plan",
    backToTimer: "Back to Timer",
    reviewFlashcards: "Review Flashcards",
    takeQuiz: "Take Quiz",
    grade: "Grade",
    done: "Done",
    leaderboard: "Leaderboard",
    flashcards: "Flashcards",
    // ... New Features ...
    gameCenter: "Game Center",
    social: "Social",
    battleMode: "Battle Mode",
    zenMode: "Zen Mode",
    focusShield: "Focus Shield",
    pet: "Focus Pet",
    market: "Stock Market",
    shop: "Item Shop",
    guilds: "Guilds",
    lounge: "Study Lounge",
    essayGrader: "Essay Grader",
    podcastGen: "Podcast Gen",
    conceptMap: "Concept Map",
    examSim: "Exam Simulator",
    eyeYoga: "Eye Yoga",
    eisenhower: "Eisenhower Matrix",
    timeline: "Timeline",
    mood: "Mood",
    howAreYou: "How are you feeling?",
    accentColor: "Accent Color",
    coins: "Lumina Coins",
    buy: "Buy",
    owned: "Owned",
    hp: "HP",
    typingAsmr: "Typing ASMR",
    generateReport: "Weekly Report",
    bossDefeated: "Boss Defeated!",
    streakFreeze: "Streak Freeze",
    feedPet: "Feed Pet",
  },
  [Language.HU]: {
    // ... Existing ...
    login: 'Bejelentkezés',
    register: 'Regisztráció',
    username: 'Felhasználónév',
    password: 'Jelszó',
    welcome: 'Üdv újra',
    startJourney: 'Kezdd el az utazást',
    dashboard: 'Irányítópult',
    subjects: 'Tantárgyak',
    achievements: 'Eredmények',
    history: 'Előzmények',
    settings: 'Beállítások',
    focus: 'Fókusz',
    shortBreak: 'Rövid szünet',
    longBreak: 'Hosszú szünet',
    start: 'Indítás',
    pause: 'Szünet',
    reset: 'Visszaállítás',
    sessionComplete: 'Szakasz kész!',
    whatDidYouStudy: 'Mit tanultál?',
    selectSubject: 'Válassz tárgyat',
    saveSession: 'Mentés',
    minutes: 'perc',
    level: 'Szint',
    xp: 'TP',
    nextLevel: 'Következő szint',
    logout: 'Kijelentkezés',
    theme: 'Téma',
    language: 'Nyelv',
    addSubject: 'Tárgy hozzáadása',
    subjectName: 'Tantárgy neve',
    create: 'Létrehozás',
    cancel: 'Mégse',
    totalTime: 'Összes idő',
    aiTip: 'AI Tanulási Tipp',
    getAiTip: 'Kérj AI Motivációt',
    loadingAi: 'Gondolkodik...',
    noAccount: "Nincs még fiókod?",
    hasAccount: "Már van fiókod?",
    enterDetails: "Add meg a részleteket a TP megszerzéséhez!",
    notesPlaceholder: "Ma arról tanultam, hogy...",
    volume: "Háttérzaj Hangerő",
    dailyQuests: "Napi Küldetések",
    rankings: "Ranglista",
    aiLab: "AI Labor",
    explainConcept: "Fogalom Magyarázat",
    explainPlaceholder: "pl. Kvantumfizika, Francia forradalom...",
    simplify: "Egyszerűsítsd",
    studyPlanner: "Tanulási Terv",
    plannerPlaceholder: "pl. Van 2 órám a Biológia vizsgára...",
    generatePlan: "Terv Készítése",
    backToTimer: "Vissza az órához",
    reviewFlashcards: "Kártyák Áttekintése",
    takeQuiz: "Kvíz Kitöltése",
    grade: "Értékelés",
    done: "Kész",
    leaderboard: "Ranglista",
    flashcards: "Tanulókártyák",
    // ... New Features ...
    gameCenter: "Játék Központ",
    social: "Közösség",
    battleMode: "Csata Mód",
    zenMode: "Zen Mód",
    focusShield: "Fókusz Pajzs",
    pet: "Fókusz Kisállat",
    market: "Tőzsde",
    shop: "Bolt",
    guilds: "Céhek",
    lounge: "Tanulószoba",
    essayGrader: "Esszé Javító",
    podcastGen: "Podcast Generátor",
    conceptMap: "Fogalomtérkép",
    examSim: "Vizsga Szimulátor",
    eyeYoga: "Szem Jóga",
    eisenhower: "Eisenhower Mátrix",
    timeline: "Idővonal",
    mood: "Hangulat",
    howAreYou: "Hogy érzed magad?",
    accentColor: "Kiemelő Szín",
    coins: "Lumina Érmék",
    buy: "Vásárlás",
    owned: "Birtokolt",
    hp: "Élet",
    typingAsmr: "Gépelés ASMR",
    generateReport: "Heti Jelentés",
    bossDefeated: "Főnök Legyőzve!",
    streakFreeze: "Széria Fagyasztó",
    feedPet: "Állat Etetése",
  }
};
